version: 4.4

orbs:
  react-native: circleci/react-native@1.0.1

jobs:
  build:
    executor:
      name: react-native/android
    steps:
      - checkout
      - react-native/install
      - run:
          name: Build APK
          command: |
            cd android && ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  build:
    jobs:
      - build
