version: 4.2
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install JDK and Android SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-8-jdk
            sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
            curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
            mkdir android-sdk-linux
            unzip -d android-sdk-linux sdk-tools.zip
            rm sdk-tools.zip
            echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"
            echo y | android-sdk-linux/tools/bin/sdkmanager --licenses
            export ANDROID_HOME=$PWD/android-sdk-linux
            export PATH=$PATH:$PWD/android-sdk-linux/platform-tools:$PWD/android-sdk-linux/tools
            echo 'export ANDROID_HOME=$PWD/android-sdk-linux' >> $BASH_ENV
            echo 'export PATH=$PATH:$PWD/android-sdk-linux/platform-tools:$PWD/android-sdk-linux/tools' >> $BASH_ENV
      - run:
          name: Install Node.js and Yarn
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g yarn
      - run:
          name: Install app dependencies
          command: |
            yarn install
      - run:
          name: Build release APK
          command: |
            cd android
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release-unsigned.apk
