version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: |
          apt-get update && \
          apt-get install -y openjdk-11-jdk && \
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - run: npx react-native doctor
      - run: pwd
      - run: npx react-native info
      - run:
          name: Build APK
          command: npx react-native run-android --variant=release
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
