version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install
            npx jetify
      - run:
          name: Build APK
          command: |
            cd android && ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build
