version: 3.5
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Set up Android SDK
          command: |
            echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "extras;android;m2repository" "extras;google;m2repository"
            echo y | android-sdk-linux/tools/bin/sdkmanager --licenses
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build APK
          command: npx react-native run-android --variant=release
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
