version: 4.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yes | sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
      - run:
          name: Set Android Home Environment Variable
          command: |
            echo 'export ANDROID_HOME=/usr/local/android-sdk-linux' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install React Native CLI
          command: npm install -g react-native-cli
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Android APK
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleDebug
      - store_artifacts:
          path: android/app/build/outputs/apk/debug/app-debug.apk
